2020-02-09 09:23:40 INFO  cn.com.alasky.StartApp 26 main - 启动应用
2020-02-09 09:23:41 INFO  org.springframework.boot.StartupInfoLogger 50 logStarting - Starting StartApp on Alasky with PID 2488 (F:\develop\association\target\classes started by Alasky in F:\develop\association)
2020-02-09 09:23:41 INFO  org.springframework.boot.SpringApplication 675 logStartupProfileInfo - No active profile set, falling back to default profiles: default
2020-02-09 09:23:43 INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate 244 multipleStoresDetected - Multiple Spring Data modules found, entering strict repository configuration mode!
2020-02-09 09:23:43 INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate 126 registerRepositoriesIn - Bootstrapping Spring Data repositories in DEFAULT mode.
2020-02-09 09:23:43 INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate 182 registerRepositoriesIn - Finished Spring Data repository scanning in 71ms. Found 0 repository interfaces.
2020-02-09 09:23:44 INFO  org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker 330 postProcessAfterInitialization - Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$5d52d17c] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-02-09 09:23:44 INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer 90 initialize - Tomcat initialized with port(s): 8080 (http)
2020-02-09 09:23:44 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Initializing ProtocolHandler ["http-nio-8080"]
2020-02-09 09:23:44 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Starting service [Tomcat]
2020-02-09 09:23:44 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Starting Servlet engine: [Apache Tomcat/9.0.16]
2020-02-09 09:23:44 INFO  org.apache.juli.logging.DirectJDKLog 173 log - The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [C:\Software\java\jdk1.8.0_211\bin;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Software\python\Scripts\;C:\Software\python\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Software\java\jdk1.8.0_211\bin;C:\Software\java\jdk1.8.0_211\jre\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;D:\hadoop-2.7.1\bin;%CATALINA_HOME%\lib;%CATALINA_HOME%\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Software\Git\cmd;D:\mysql-8.0.18-winx64\bin;C:\Software\python\python3.6\Scripts\;C:\Software\python\python3.6\;C:\Software\Scripts\;C:\Software\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;D:\IntelliJ IDEA 2019.1.2\bin;D:\Microsoft VS Code\bin;D:\apache-maven-3.6.1\bin;C:\Software\python\Scripts;.]
2020-02-09 09:23:45 INFO  org.apache.juli.logging.DirectJDKLog 173 log - At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2020-02-09 09:23:45 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Initializing Spring embedded WebApplicationContext
2020-02-09 09:23:45 INFO  org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext 296 prepareWebApplicationContext - Root WebApplicationContext: initialization completed in 3341 ms
2020-02-09 09:23:46 INFO  io.lettuce.core.EpollProvider 68 <clinit> - Starting without optional epoll library
2020-02-09 09:23:46 INFO  io.lettuce.core.KqueueProvider 70 <clinit> - Starting without optional kqueue library
2020-02-09 09:23:48 INFO  org.springframework.scheduling.concurrent.ExecutorConfigurationSupport 171 initialize - Initializing ExecutorService 'applicationTaskExecutor'
2020-02-09 09:23:49 INFO  org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor 295 finishRegistration - No TaskScheduler/ScheduledExecutorService bean found for scheduled processing
2020-02-09 09:23:49 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Starting ProtocolHandler ["http-nio-8080"]
2020-02-09 09:23:49 INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer 204 start - Tomcat started on port(s): 8080 (http) with context path ''
2020-02-09 09:23:49 INFO  org.springframework.boot.StartupInfoLogger 59 logStarted - Started StartApp in 8.341 seconds (JVM running for 10.81)
2020-02-09 09:24:34 INFO  org.apache.juli.logging.DirectJDKLog 173 log - Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-02-09 09:24:34 INFO  org.springframework.web.servlet.FrameworkServlet 524 initServletBean - Initializing Servlet 'dispatcherServlet'
2020-02-09 09:24:34 INFO  org.springframework.web.servlet.FrameworkServlet 546 initServletBean - Completed initialization in 8 ms
2020-02-09 11:46:33 INFO  io.netty.util.internal.logging.AbstractInternalLogger 219 log - [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。] Unexpected exception during request: [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。]
2020-02-09 11:46:33 INFO  io.netty.util.internal.logging.AbstractInternalLogger 219 log - [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。] Unexpected exception during request: [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。]
2020-02-09 11:46:34 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was /192.168.8.101:6379
2020-02-09 11:46:34 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was /192.168.8.101:6379
2020-02-09 11:46:34 WARN  io.netty.util.internal.logging.AbstractInternalLogger 199 log - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: no further information: /192.168.8.101:6379 io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: no further information: /192.168.8.101:6379
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_211]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_211]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.net.NoRouteToHostException: No route to host: no further information
	... 11 more

2020-02-09 11:46:34 WARN  io.netty.util.internal.logging.AbstractInternalLogger 199 log - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: no further information: /192.168.8.101:6379 io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: No route to host: no further information: /192.168.8.101:6379
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_211]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_211]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327) ~[netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) [netty-transport-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.33.Final.jar:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.net.NoRouteToHostException: No route to host: no further information
	... 11 more

2020-02-09 11:46:44 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-02-09 11:46:44 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-02-09 11:46:44 INFO  io.lettuce.core.protocol.ReconnectionHandler 177 lambda$null$3 - Reconnected to 192.168.8.101:6379
2020-02-09 11:46:45 INFO  io.lettuce.core.protocol.ReconnectionHandler 177 lambda$null$3 - Reconnected to 192.168.8.101:6379
2020-02-09 12:35:29 INFO  io.netty.util.internal.logging.AbstractInternalLogger 219 log - [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。] Unexpected exception during request: [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。]
2020-02-09 12:35:29 INFO  io.netty.util.internal.logging.AbstractInternalLogger 219 log - [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。] Unexpected exception during request: [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。]
2020-02-09 12:35:29 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was /192.168.8.101:6379
2020-02-09 12:35:29 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was /192.168.8.101:6379
2020-02-09 15:04:20 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: java.util.concurrent.TimeoutException: Reconnection attempt exceeded timeout of 60 SECONDS 
2020-02-09 15:04:20 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: java.util.concurrent.TimeoutException: Reconnection attempt exceeded timeout of 60 SECONDS 
2020-02-09 15:04:20 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-02-09 15:04:20 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-02-09 15:04:30 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-02-09 15:04:30 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-02-09 15:04:30 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-02-09 15:04:30 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-02-09 15:04:30 INFO  io.lettuce.core.protocol.ReconnectionHandler 177 lambda$null$3 - Reconnected to 192.168.8.101:6379
2020-02-09 15:04:30 INFO  io.lettuce.core.protocol.ReconnectionHandler 177 lambda$null$3 - Reconnected to 192.168.8.101:6379
2020-02-09 15:42:17 INFO  io.netty.util.internal.logging.AbstractInternalLogger 219 log - [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。] Unexpected exception during request: [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。]
2020-02-09 15:42:17 INFO  io.netty.util.internal.logging.AbstractInternalLogger 219 log - [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。] Unexpected exception during request: [null, java.io.IOException: 远程主机强迫关闭了一个现有的连接。, java.io.IOException: 远程主机强迫关闭了一个现有的连接。]
2020-02-09 15:42:17 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was /192.168.8.101:6379
2020-02-09 15:42:17 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was /192.168.8.101:6379
2020-02-09 15:43:18 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: java.util.concurrent.TimeoutException: Reconnection attempt exceeded timeout of 60 SECONDS 
2020-02-09 15:43:18 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: java.util.concurrent.TimeoutException: Reconnection attempt exceeded timeout of 60 SECONDS 
2020-02-09 15:43:18 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-02-09 15:43:18 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-02-09 15:43:28 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-02-09 15:43:28 WARN  io.netty.util.internal.logging.AbstractInternalLogger 176 log - Cannot reconnect: io.netty.channel.ConnectTimeoutException: connection timed out: /192.168.8.101:6379
2020-02-09 15:43:28 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-02-09 15:43:28 INFO  io.netty.util.internal.logging.AbstractInternalLogger 173 log - Reconnecting, last destination was 192.168.8.101:6379
2020-02-09 15:43:28 INFO  io.lettuce.core.protocol.ReconnectionHandler 177 lambda$null$3 - Reconnected to 192.168.8.101:6379
2020-02-09 15:43:29 INFO  io.lettuce.core.protocol.ReconnectionHandler 177 lambda$null$3 - Reconnected to 192.168.8.101:6379
